djangoBookweb/urls.py
from django.contrib import admin
from django.urls import path
from Bookweb.views import MainView, AddBookView, RegisterView, LoginView, LogoutView, AddAuthorView, GenresListView, \
    GenreDetailView, AuthorListView, AuthorDetailView, BookDetailView, UserProfile, UserInterface, \
    UsersListView, ChangeDataAccount, PublishersListView, PublisherDetailView, PublicationDetailView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainView.as_view(), name='index'),
    path('register/', RegisterView.as_view(), name='register'),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('add_book/', AddBookView.as_view(), name='add_book'),
    path('add_author/', AddAuthorView.as_view(), name='add_author'),
    path('genres/', GenresListView.as_view(), name='genres'),
    path('genre/<int:pk>/', GenreDetailView.as_view(), name='genre_detail'),
    path('authors/', AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>/', AuthorDetailView.as_view(), name='author_detail'),
    path('book/<int:pk>/', BookDetailView.as_view(), name='book_detail'),
    path('profile/<int:pk>/', UserProfile.as_view(), name='profile_detail'),
    path('user_interface/<int:pk>/', UserInterface.as_view(), name='user_interface'),
    path('accounts/<int:pk>/update/', ChangeDataAccount.as_view(), name='user_edit'),
    path('users/', UsersListView.as_view(), name='users'),
    path('publishers/', PublishersListView.as_view(), name='publishers'),
    path('publisher/<int:pk>/', PublisherDetailView.as_view(), name='publisher_detail'),
    path('publication/<int:pk>/', PublicationDetailView.as_view(), name='publication_detail')

]

Bookweb/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

GRADES = (
    (1, "1"),
    (2, "2"),
    (3, "3"),
    (4, "4"),
    (5, "5"),
    (6, "6"),
    (7, "7"),
    (8, "8"),
    (9, "9"),
    (10, "10")
)


class Genres(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    description = models.TextField()

    @property
    def avg_grade(self):
        books = self.books_set.all()
        sum = 0
        grades = 0
        if len(list(books)) == 0:
            return 'brak dodanych książek'
        for book in books:
            for gread in book.bookgrades_set.all():
                sum += gread.grade
                grades += 1
            if grades == 0:
                return "brak ocen"
            else:
                return sum / grades
        return sum / grades

    def __str__(self):
        return self.first_name + ' ' + self.last_name


class Books(models.Model):
    title = models.CharField(max_length=250)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    description = models.TextField()
    genre = models.ManyToManyField(Genres, through="Book_Genres")
    accepted = models.BooleanField(default=False)

    @property
    def avg_grade(self):
        sum = 0
        grades = 0
        for grade in self.bookgrades_set.all():
            sum += grade.grade
            grades += 1
        if grades == 0:
            return "brak ocen"
        else:
            return sum / grades

    def publications(self):
        return list(self.publication_set.all())

    def __str__(self):
        return self.title


class BookGrades(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    grade = models.IntegerField(choices=GRADES)
    comment = models.TextField(null=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'book'], name='dzieciol')
        ]

    @property
    def name(self):
        return "{} | {} | {}".format(self.user, self.grade, self.book)



    def __str__(self):
        return self.name


class Publisher(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name


class Publication(models.Model):
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    publication_year = models.IntegerField()

    def __str__(self):
        return self.name




    @property
    def name(self):
        return "{} | {} | {}".format(self.book, self.publication_year, self.publisher)

    def __str__(self):
        return self.name


class Book_Genres(models.Model):
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    genre = models.ForeignKey(Genres, on_delete=models.CASCADE)

    @property
    def name(self):
        return "{} || {}".format(self.book, self.genre)

    def __str__(self):
        return self.name

class PublicationComments(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    publication = models.ForeignKey(Publication, on_delete=models.CASCADE)
    comment = models.TextField(null=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'publication'], name='dzieciol2')
        ]

    @property
    def name(self):
        return "{} | {} | {} | {}".format(self.user, self.publication.book.title, self.publication.publication_year, self.publication.publisher)

    def __str__(self):
        return self.name

templates/add_author.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block content %}
    <meta charset="UTF-8">
    <title>Title</title>
</head>

<body>
<h2>Dodaj Autora:</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Dodaj">
    </form>
{% endblock %}

</body>
</html>

templates/add_book.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>Title</title>
</head>
{% block content %}
<body>
<a href="/">Strona Główna</a>
<h2>Dodaj Książkę:</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Dodaj">
    </form>
</body>
{% endblock %}
</html>

templates/author_details.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ author.first_name }} {{ author.last_name }} </h1>
<p> {{ author.description }}</p>

<p>Średnia ocen: {{ author.avg_grade }}</p>

<h2>KSIĄŻKI AUTORA:</h2>
{% for book in author.books_set.all %}
    <li><a href="/book/{{ book.id }}">{{ book.title }}</a> {{ book.avg_grade }}</li>
    <ul>{{ book.description }}</ul>
{% endfor %}
{% endblock %}
</body>
</html>

templates/author_list.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block content %}
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for each in author %}
    <li><a href="/author/{{ each.id }}">{{ each.first_name }} {{ each.last_name }}</a></li>
{% endfor %}
</body>
{% endblock %}
</html>

templates/base.html
<!doctype html>
    {%  load static %}
<html>

    <head>

        <meta charset="utf-8">
        <title> &#128526; Bookweb.</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

{#    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css">#}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     </head>

    <body>
<div class="wrapper">
    <header>
<nav class="nav navbar-nav navbar-expand-lg fixed-top" role="navigation">
                <div class="container">
                    <div class="logo">
                        <a href="/"><img src="static/img/logo2.png"></a>
                    </div>
                    <ul>
                        <li><a href="/add_author/">Dodaj Autora.</a></li>
                        <li><a href="/add_book/">Dodaj Książkę.</a></li>

{#            <li><a href="/">Strona główna</a> </li>#}
            {% if user.is_authenticated %}
        <li class="log"><a href="/profile/{{ user.id }}">{{ request.user }}</a></li><li class="log"><a href="/logout/"> Wyloguj</a></li>
            <li class="log"><a href="/user_interface/{{ user.id }}">Panel Użytkownika</a></li>
        {%  else %}
                        <li class="log"><a href="/accounts/login/">Zaloguj</a></li>
                        <li class="log"><a href="/register/">&nbspZarejestruj</a></li>
                        {% endif %}


                    </ul>
                </div>
            </nav>
    <div class="header page-header" style="background-image: url(static/img/background.png);">
                <div class="header-title">
                    <div class="text-content text-center">

{#                        -----------------------------------------------------------------wyszukiwarka#}
                        {% block content %}
                            <h1 class="headline presentation-subtitle">Bookweb.</h1>
                        <h2 class="subheadline">Oceniaj książki - nie po okładce!</h2>
                           <form class="search" method="post">

        {% csrf_token %}
        {{ form_search.as_p }}
        <input type="submit" value="Szukaj">
    </form>
{#                        --------------------------------------------------------------------------------#}
                    </div>
                </div>
            </div>
</header>

        <div class="col-12 text-center results">
            <ul>
        {% for each in search_author %}
            <li><a href="/author/{{ each.id }}"> {{ each }}</a></li>
        {% endfor %}
    </ul>
    <ul>
        {% for each in search_book %}
            <li><a href="/book/{{ each.id }}"> {{ each }}</a></li>
        {% endfor %}
    </ul>
    <ul>
        {% for each in search_publisher %}
            <li><a href="/publisher/{{ each.id }}"> {{ each }}</a></li>
        {% endfor %}
    </ul>

</div>

        </div>
<div class="aboutus-area" id=about>
                <div class="container">
                    <div class="row">
                            <div class="col-12">
                                <h1><span>O nas</span></h1>
                                <div class="aboutus-content col-8 d-print-inline col-md-offset-3">

                                    <h2>Bookweb <span>to my!</span></h2>

                                    <p class="d-print-inline">Jesteśmy jedynym najlepszym portalem służącym do oceny publikacji książkowych w całej Polsce! Dołącz do nas i korzystaj z możliwości publikacji własnych recenzji książkowych, oraz ocen, aby świat fanów literatury uczynić lżejszym i przyjemniejszym!</p>


{#                                    <div class="counter ">#}
{#                                        <div class="col-12">#}
{#                                            <div class="single-counter text-center">#}
{#                                                <h2 class="counter"><span>15</span></h2>#}
{#                                                <p>UŻYTKOWNIKÓW</p>#}
{#                                            </div>#}
{##}
{#                                            <div class="single-counter text-center">#}
{#                                                <h2 class="counter"><span>100</span></h2>#}
{#                                                <p>DODANYCH KSIĄŻEK</p>#}
{#                                            </div>#}
{##}
{#                                            <div class="single-counter text-center">#}
{#                                                <h2 class="counter"><span>5</span></h2>#}
{#                                                <p>WYSTAWIONYCH RECENZJI</p>#}
{#                                            </div>#}
{##}
{#                                            <div class="single-counter text-center">#}
{#                                                <h2 class="counter"><span>10</span></h2>#}
{#                                                <p>DODANYCH ZDJĘĆ</p>#}
{#                                            </div>#}
{#                                        </div>#}
{#                                    </div>#}
                                </div>
                                <!-- <img src="img/about.jpg" class="about-img col-12 col-sm-6 float-right d-print-inline">  -->
                            </div>
                    </div>
                </div>
            </div>
{% endblock %}
{#    <footer>#}
{#        <div class="container">#}
{#        </div>#}
{#    </footer>#}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

        </body>

</html>

templates/book_details.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block content %}
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ book.title }}</h1> <h4>Ocena: {{ book.avg_grade }}</h4>
<p>Autor: <a href="/author/{{ book.author_id }}"> {{ book.author }}</a></p>

{#{% for each in book.author_set.all %}#}
{#    <li><a href="/author/{{ author.id }}">{{ book.author }}</a> {{ author.avg_grade }}</li>#}
{#    <ul>{{ author.description }}</ul>#}
{#{% endfor %}#}
Wydania:
{% for book in book.publications %}
    <li><a href="/publication/{{ book.publisher.id }}">  {{ book.publisher.name }} {{ book.publication_year }} </a></li>
{% endfor %}

<p>Komentarze:</p>
<form method="post">
        {% csrf_token %}
        {{ add_comment.as_p }}
        <input type="submit" value="Dodaj Ocene">
    </form>
{% for comment in book.bookgrades_set.all %}
    <li><a href="/profile/{{ comment.user.id }}">{{ comment.user }}</a>: {{ comment.grade }}</li>
    <p>{{ comment.comment }}</p>
{% endfor %}
{% endblock %}
</body>
</html>

templates/genres_list.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>{% block content %}
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for genre in genres %}
    <li><a href="/genre/{{ genre.id }}">{{ genre.name }}</a></li>
{% endfor %}{% endblock %}
</body>
</html>

templates/login.html
{% extends 'base.html' %}
<head>
</head>
<body>
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Zaloguj">
</form>
{% endblock %}
</body>




{##}
{#{% extends 'base.html' %}#}
{##}
{#{% block title %}Logowanie{% endblock %}#}
{##}
{#{% block content %}#}
{#    <form method="post">#}
{#       <h2>Logowanie</h2>#}
{#    {% csrf_token %}#}
{#    {{ form.as_p }}#}
{#    <input type="submit" value="zaloguj">#}
{#    </form>#}
{#{% endblock %}#}

templates/publisher_details.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>{% block content %}
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ publisher.name }}</h1>
{{ publisher.description }}
<p>Książki wydawnictwa:</p>
{% for book in publisher.publication_set.all %}
    <li><a href="/publication/{{ book.id }}">{{ book.book.title }} {{ book.publication_year }}</a> {{ book.book.avg_grade }}</li>
    <ul>{{ book.description }}</ul>
{% endfor %}
{% endblock %}
</body>
</html>

templates/publisher_list.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>{% block content %}
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="/">Strona Główna</a>
<h1>LISTA WYDAWNICTW:</h1>
{% for each in publishers %}
    <li><a href="/publisher/{{ each.id }}">{{ each.name }}</a></li>
{% endfor %}{% endblock %}
</body>
</html>

templates/register.html
{% extends 'base.html' %}

{% block title %}Rejestracja{% endblock %}

{% block content %}
    <form method="post">
       <h2>Rejestracja</h2>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Rejestruj">
    </form>
{% endblock %}

templates/user_edit.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Edytuj">
    </form>
{% endblock %}

templates/user_interface.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="interface ">
<div class="col-12 ">


{#{% if user.is_authenticated %}#}
<table class="table ">
<ul><a href="/profile/{{ user.id }}">{{ user }}</a></ul>

<ul>    <a href="/accounts/{{ user.id }}/update/">Edytuj</a></ul>
<ul>    <a href="/logout/"> Wyloguj</a></ul>
<p>Twoje ostatnie komentarze:</p>
{% for comment in user.bookgrades_set.all %}
    <li><a href="/book/{{ comment.book.id }}">{{ comment.book }}</a> |
        <a href="/author/{{ comment.book.author.id }}">{{ comment.book.author }}</a></li>
    <ul>{{ comment.grade }} | {{ comment.comment }}</ul></table>
    </div>
    </div>
{% endfor %}
{% endblock %}
{#        {%  else %}#}
{#          <a href="/login/">Zaloguj</a>#}
{#            <p style="display: inline-block;">||</p>#}
{#          <a href="/register/">&nbspZarejestruj</a>#}
{#{% endif %}#}
</body>
</html>

templates/user_profile.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ user.username }}</h1>
<p><b>Z nami od:</b> {{ user.date_joined }}</p>
<p>Ostatnie komentarze:</p>
{% for comment in user.bookgrades_set.all %}
    <li><a href="/book/{{ comment.book.id }}">{{ comment.book }}</a> |
        <a href="/author/{{ comment.book.author.id }}">{{ comment.book.author }}</a></li>
    <ul>{{ comment.grade }} | {{ comment.comment }}</ul>
{% endfor %}

{% endblock %}
</body>
</html>